### ISSUE TITLE
Fix dryer_cycle_complete_3 automation service call error

### ISSUE THREAD

**Issue by festion** [festion/home-assistant-config#4]
## Issue Description
The `dryer_cycle_complete_3` automation is failing with the following error:
```
Logger: homeassistant.components.automation.dryer_cycle_complete_3
Source: helpers/script.py:2067
integration: Automation (documentation, issues)
First occurred: 3:35:26 PM (1 occurrence)
Last logged: 3:35:26 PM
Dryer - Cycle Complete: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['entity_id']
```

## Root Cause
The automation in `automations/missing_automations_restored.yaml` is using the deprecated `notify.alexa_media` service call format with `target: entity_id` structure, which is no longer supported.

## Solution
Update the service call to use the correct `notify.alexa_media_everywhere` format as documented in the alexa_media_player_service_calls memory.

### Before (Broken):
```yaml
- service: notify.alexa_media
  target:
    entity_id: media_player.everywhere
  data:
    message: "..."
```

### After (Fixed):
```yaml
- service: notify.alexa_media_everywhere
  data:
    message: "..."
    data:
      type: announce
```

## Files Affected
- `automations/missing_automations_restored.yaml`

## Testing
- [x] YAML syntax validation passed
- [x] Code linting validation completed
- [ ] Deploy and test automation trigger

## Related
This follows the same pattern used to fix other appliance automations in the appliances.yaml file.
